variables:
  # Commit of ghc/ci-images repository from which to pull Docker images
  DOCKER_REV: 3f731f5d37a156e7ebe10cd32656946083baaf4a

.build:
  script:
    - cabal update
    - cabal v2-install cabal-install --installdir=$(pwd)/out --install-method=copy --overwrite-policy=always
  artifacts:
    expire_in: 2 week
    paths:
      - out

build-aarch64-linux-deb9:
  extends: .build
  tags:
    - aarch64-linux
  image: "registry.gitlab.haskell.org/ghc/ci-images/aarch64-linux-deb9:$DOCKER_REV"

build-armv7-linux-deb9:
  extends: .build
  tags:
    - armv7-linux
  image: "registry.gitlab.haskell.org/ghc/ci-images/armv7-linux-deb9:$DOCKER_REV"

build-x86_64-linux:
  extends: .build
  tags:
    - x86_64-linux
  image: "registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-deb9:$DOCKER_REV"

build-x86_64-freebsd:
  extends: .build
  tags:
    - x86_64-freebsd
  image: "registry.gitlab.haskell.org/ghc/ci-images/x86_64-freebsd:$DOCKER_REV"

build-x86_64-linux-alpine:
  extends: .build
  tags:
    - x86_64-linux
  image: "registry.gitlab.haskell.org/ghc/ci-images/x86_64-linux-alpine:$DOCKER_REV"
